#!/usr/bin/env python3
"""Export the generated Mini-GPT slide images to a PPTX with speaker notes.

This avoids adding a project package manager just to assemble the final deck.
The slide images are generated by the baoyu prompt workflow and live in
share/deck/NN-slide-*.png. Speaker notes come from microgpt_deck_data.mjs.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
DECK_DIR = ROOT / "share" / "deck"
OUT = DECK_DIR / "build-mini-gpt-from-scratch.pptx"
TMP_JSON = ROOT / "tmp" / "microgpt_slides.json"

SLIDE_CX = 12192000
SLIDE_CY = 6858000


def load_slides() -> list[dict]:
    TMP_JSON.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "import('./tools/microgpt_deck_data.mjs').then(m=>"
        "process.stdout.write(JSON.stringify(m.slides)))"
    )
    result = subprocess.run(
        ["node", "-e", js],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return json.loads(result.stdout)


def two(n: int) -> str:
    return f"{n:02d}"


def media_name(index: int) -> str:
    return f"image{index}.png"


def image_path(slide: dict) -> Path:
    return DECK_DIR / f"{two(slide['n'])}-slide-{slide['slug']}.png"


def xml_text(text: str) -> str:
    return escape(text, {"'": "&apos;", '"': "&quot;"})


def para(text: str) -> str:
    text = xml_text(text)
    return (
        '<a:p><a:pPr marL="0" indent="0"/>'
        f'<a:r><a:rPr lang="en-US" sz="1600"/><a:t>{text}</a:t></a:r>'
        "</a:p>"
    )


def notes_paragraphs(notes: list[str]) -> str:
    paragraphs: list[str] = []
    for block in notes:
        for line in re.split(r"\n+", block):
            line = line.strip()
            if line:
                paragraphs.append(para(line))
    return "".join(paragraphs)


def content_types(slides: list[dict]) -> str:
    slide_overrides = "\n".join(
        f'<Override PartName="/ppt/slides/slide{i}.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
        f'\n<Override PartName="/ppt/notesSlides/notesSlide{i}.xml" '
        'ContentType="application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml"/>'
        for i in range(1, len(slides) + 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="png" ContentType="image/png"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>
  <Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>
  <Override PartName="/ppt/notesMasters/notesMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml"/>
  <Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>
{slide_overrides}
</Types>'''


def root_rels() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>'''


def app_xml(slides: list[dict]) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
  xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Codex</Application>
  <PresentationFormat>On-screen Show (16:9)</PresentationFormat>
  <Slides>{len(slides)}</Slides>
  <Notes>{len(slides)}</Notes>
</Properties>'''


def core_xml() -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:dcmitype="http://purl.org/dc/dcmitype/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>Build a Mini-GPT from scratch</dc:title>
  <dc:creator>Codex</dc:creator>
  <cp:lastModifiedBy>Codex</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">{now}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">{now}</dcterms:modified>
</cp:coreProperties>'''


def presentation_xml(slides: list[dict]) -> str:
    slide_ids = "\n".join(
        f'<p:sldId id="{255 + i}" r:id="rId{i}"/>'
        for i in range(1, len(slides) + 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId{len(slides)+1}"/></p:sldMasterIdLst>
  <p:notesMasterIdLst><p:notesMasterId r:id="rId{len(slides)+2}"/></p:notesMasterIdLst>
  <p:sldIdLst>
{slide_ids}
  </p:sldIdLst>
  <p:sldSz cx="{SLIDE_CX}" cy="{SLIDE_CY}" type="wide"/>
  <p:notesSz cx="6858000" cy="9144000"/>
  <p:defaultTextStyle/>
</p:presentation>'''


def presentation_rels(slides: list[dict]) -> str:
    rels = []
    for i in range(1, len(slides) + 1):
        rels.append(
            f'<Relationship Id="rId{i}" '
            'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" '
            f'Target="slides/slide{i}.xml"/>'
        )
    rels.append(
        f'<Relationship Id="rId{len(slides)+1}" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" '
        'Target="slideMasters/slideMaster1.xml"/>'
    )
    rels.append(
        f'<Relationship Id="rId{len(slides)+2}" '
        'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster" '
        'Target="notesMasters/notesMaster1.xml"/>'
    )
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
        + "\n".join(rels)
        + "\n</Relationships>"
    )


def color_fill(color: str, alpha: int | None = None) -> str:
    alpha_xml = f'<a:alpha val="{alpha}"/>' if alpha is not None else ""
    return f'<a:solidFill><a:srgbClr val="{color}">{alpha_xml}</a:srgbClr></a:solidFill>'


def line_fill(color: str, alpha: int | None = None, width: int = 12700) -> str:
    return f'<a:ln w="{width}">{color_fill(color, alpha)}</a:ln>'


def shape_rect(
    shape_id: int,
    name: str,
    x: int,
    y: int,
    cx: int,
    cy: int,
    fill: str,
    line: str | None = None,
    geom: str = "rect",
) -> str:
    line_xml = line if line is not None else '<a:ln><a:noFill/></a:ln>'
    return f'''<p:sp>
        <p:nvSpPr><p:cNvPr id="{shape_id}" name="{xml_text(name)}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
          <a:prstGeom prst="{geom}"><a:avLst/></a:prstGeom>
          {fill}
          {line_xml}
        </p:spPr>
      </p:sp>'''


def text_box(
    shape_id: int,
    name: str,
    text: str,
    x: int,
    y: int,
    cx: int,
    cy: int,
    size: int,
    color: str = "F5F9FF",
    bold: bool = False,
    anchor: str = "t",
    align: str | None = None,
) -> str:
    bold_xml = ' b="1"' if bold else ""
    align_xml = f'<a:pPr algn="{align}"/>' if align else "<a:pPr/>"
    return f'''<p:sp>
        <p:nvSpPr><p:cNvPr id="{shape_id}" name="{xml_text(name)}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>
          <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
          <a:noFill/>
          <a:ln><a:noFill/></a:ln>
        </p:spPr>
        <p:txBody>
          <a:bodyPr wrap="square" anchor="{anchor}"/>
          <a:lstStyle/>
          <a:p>
            {align_xml}
            <a:r><a:rPr lang="en-US" sz="{size}"{bold_xml}>{color_fill(color)}<a:latin typeface="Aptos"/></a:rPr><a:t>{xml_text(text)}</a:t></a:r>
          </a:p>
        </p:txBody>
      </p:sp>'''


def cover_slide_xml() -> str:
    shapes: list[str] = []
    sid = 2

    shapes.append(shape_rect(sid, "Background", 0, 0, SLIDE_CX, SLIDE_CY, color_fill("07182E"))); sid += 1

    grid_w = 12700
    for x in range(0, SLIDE_CX, 762000):
        shapes.append(shape_rect(sid, "Grid vertical", x, 0, grid_w, SLIDE_CY, color_fill("55D7FF", 9000))); sid += 1
    for y in range(0, SLIDE_CY, 762000):
        shapes.append(shape_rect(sid, "Grid horizontal", 0, y, SLIDE_CX, grid_w, color_fill("55D7FF", 9000))); sid += 1

    shapes.append(
        shape_rect(
            sid,
            "Frame",
            365760,
            365760,
            SLIDE_CX - 731520,
            SLIDE_CY - 731520,
            "<a:noFill/>",
            line_fill("55D7FF", 42000, 19050),
            "roundRect",
        )
    ); sid += 1

    shapes.append(text_box(sid, "Title 1", "Build a", 914400, 1220000, 5200000, 760000, 5200, "F5F9FF", True)); sid += 1
    shapes.append(text_box(sid, "Title 2", "Mini-GPT", 914400, 1900000, 5600000, 900000, 6800, "55D7FF", True)); sid += 1
    shapes.append(text_box(sid, "Title 3", "from scratch", 914400, 2820000, 5400000, 720000, 4600, "F5F9FF", True)); sid += 1
    shapes.append(text_box(sid, "Subtitle", "Understand Transformer architecture and how it works.", 914400, 3800000, 5900000, 520000, 1850, "ACE7FF")); sid += 1

    pill_line = line_fill("55D7FF", 50000, 12700)
    shapes.append(shape_rect(sid, "Speaker pill", 914400, 4900000, 1830000, 430000, color_fill("07182E", 65000), pill_line, "roundRect")); sid += 1
    shapes.append(text_box(sid, "Speaker", "Speaker: Molin", 1020000, 4990000, 1600000, 240000, 1050, "F5F9FF", False, "ctr", "ctr")); sid += 1
    shapes.append(shape_rect(sid, "Team pill", 2920000, 4900000, 1650000, 430000, color_fill("07182E", 65000), pill_line, "roundRect")); sid += 1
    shapes.append(text_box(sid, "Team", "Team: ECP CIS", 3030000, 4990000, 1420000, 240000, 1050, "F5F9FF", False, "ctr", "ctr")); sid += 1

    diagram_x = 7250000
    shapes.append(text_box(sid, "Tokens label", "tokens", diagram_x, 1400000, 1500000, 260000, 850, "ACE7FF", True)); sid += 1
    token_y = 1720000
    for offset, token in enumerate(["d", "e", "n", "n"]):
        x = diagram_x + offset * 610000
        shapes.append(shape_rect(sid, f"Token {token}", x, token_y, 460000, 420000, color_fill("061528", 85000), line_fill("19D7F4", 85000, 12700), "roundRect")); sid += 1
        shapes.append(text_box(sid, f"Token text {token}", token, x, token_y + 45000, 460000, 250000, 1350, "F5F9FF", True, "ctr", "ctr")); sid += 1

    shapes.append(shape_rect(sid, "Flow one", diagram_x + 1160000, 2250000, 12700, 410000, color_fill("55D7FF", 80000))); sid += 1
    shapes.append(text_box(sid, "Block label", "Transformer block", diagram_x, 2780000, 2400000, 260000, 850, "ACE7FF", True)); sid += 1
    shapes.append(shape_rect(sid, "Transformer shell", diagram_x, 3110000, 2700000, 1350000, color_fill("061528", 78000), line_fill("55D7FF", 70000, 12700), "roundRect")); sid += 1

    for offset, label in enumerate(["attention", "MLP", "RMSNorm"]):
        y = 3290000 + offset * 360000
        shapes.append(shape_rect(sid, f"Block {label}", diagram_x + 260000, y, 2180000, 250000, color_fill("2F80ED", 27000), line_fill("55D7FF", 65000, 9525), "roundRect")); sid += 1
        shapes.append(text_box(sid, f"Block text {label}", label, diagram_x + 260000, y + 25000, 2180000, 160000, 800, "F5F9FF", True, "ctr", "ctr")); sid += 1

    shapes.append(shape_rect(sid, "Flow two", diagram_x + 1160000, 4550000, 12700, 410000, color_fill("55D7FF", 80000))); sid += 1
    shapes.append(text_box(sid, "Next label", "next token", diagram_x, 5030000, 1500000, 260000, 850, "ACE7FF", True)); sid += 1
    shapes.append(shape_rect(sid, "Next token", diagram_x, 5360000, 650000, 430000, color_fill("061528", 85000), line_fill("19D7F4", 85000, 12700), "roundRect")); sid += 1
    shapes.append(text_box(sid, "Next token text", "i", diagram_x, 5400000, 650000, 250000, 1350, "55D7FF", True, "ctr", "ctr")); sid += 1
    for offset, height in enumerate([150000, 260000, 190000, 360000, 230000]):
        shapes.append(shape_rect(sid, "Logit bar", diagram_x + 940000 + offset * 130000, 5790000 - height, 70000, height, color_fill("2F80ED" if offset != 3 else "55D7FF", 85000), None, "roundRect")); sid += 1

    shape_xml = "\n      ".join(shapes)
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      {shape_xml}
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>'''


def slide_xml(index: int, title: str) -> str:
    title = xml_text(title)
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:pic>
        <p:nvPicPr><p:cNvPr id="2" name="{title}"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr>
        <p:blipFill><a:blip r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></p:blipFill>
        <p:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="{SLIDE_CX}" cy="{SLIDE_CY}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
      </p:pic>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>'''


def slide_rels(index: int) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/{media_name(index)}"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide" Target="../notesSlides/notesSlide{index}.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
</Relationships>'''


def cover_slide_rels(index: int) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide" Target="../notesSlides/notesSlide{index}.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
</Relationships>'''


def notes_xml(slide: dict) -> str:
    notes = notes_paragraphs(slide["notes"])
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:notes xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Notes"/><p:cNvSpPr/><p:nvPr><p:ph type="body" idx="1"/></p:nvPr></p:nvSpPr>
        <p:spPr><a:xfrm><a:off x="457200" y="457200"/><a:ext cx="5943600" cy="8229600"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr>
        <p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>{notes}</p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:notes>'''


def notes_rels(index: int) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="../slides/slide{index}.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster" Target="../notesMasters/notesMaster1.xml"/>
</Relationships>'''


def slide_master_xml() -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
  <p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>
  <p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles>
</p:sldMaster>'''


def slide_master_rels() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>
</Relationships>'''


def slide_layout_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1">
  <p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sldLayout>'''


def slide_layout_rels() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/>
</Relationships>'''


def notes_master_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:notesMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/>
  <p:notesStyle/>
</p:notesMaster>'''


def notes_master_rels() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/>
</Relationships>'''


def theme_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="MiniGPT Blueprint">
  <a:themeElements>
    <a:clrScheme name="MiniGPT"><a:dk1><a:srgbClr val="07182E"/></a:dk1><a:lt1><a:srgbClr val="F5F9FF"/></a:lt1><a:dk2><a:srgbClr val="0C1020"/></a:dk2><a:lt2><a:srgbClr val="FFFFFF"/></a:lt2><a:accent1><a:srgbClr val="55D7FF"/></a:accent1><a:accent2><a:srgbClr val="2F80ED"/></a:accent2><a:accent3><a:srgbClr val="7C3AED"/></a:accent3><a:accent4><a:srgbClr val="F59E0B"/></a:accent4><a:accent5><a:srgbClr val="14B8A6"/></a:accent5><a:accent6><a:srgbClr val="F5F9FF"/></a:accent6><a:hlink><a:srgbClr val="55D7FF"/></a:hlink><a:folHlink><a:srgbClr val="2F80ED"/></a:folHlink></a:clrScheme>
    <a:fontScheme name="Aptos"><a:majorFont><a:latin typeface="Aptos Display"/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/></a:minorFont></a:fontScheme>
    <a:fmtScheme name="Office"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme>
  </a:themeElements>
</a:theme>'''


def write_pptx(slides: list[dict]) -> None:
    missing = [
        str(image_path(slide))
        for slide in slides
        if slide["n"] != 1 and not image_path(slide).exists()
    ]
    if missing:
        print("Missing slide images:", file=sys.stderr)
        for path in missing:
            print(f"- {path}", file=sys.stderr)
        sys.exit(1)

    if OUT.exists():
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = OUT.with_name(f"{OUT.stem}-backup-{timestamp}{OUT.suffix}")
        OUT.replace(backup)
        print(f"Backed up existing PPTX to {backup}")

    with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as pptx:
        pptx.writestr("[Content_Types].xml", content_types(slides))
        pptx.writestr("_rels/.rels", root_rels())
        pptx.writestr("docProps/app.xml", app_xml(slides))
        pptx.writestr("docProps/core.xml", core_xml())
        pptx.writestr("ppt/presentation.xml", presentation_xml(slides))
        pptx.writestr("ppt/_rels/presentation.xml.rels", presentation_rels(slides))
        pptx.writestr("ppt/slideMasters/slideMaster1.xml", slide_master_xml())
        pptx.writestr("ppt/slideMasters/_rels/slideMaster1.xml.rels", slide_master_rels())
        pptx.writestr("ppt/slideLayouts/slideLayout1.xml", slide_layout_xml())
        pptx.writestr("ppt/slideLayouts/_rels/slideLayout1.xml.rels", slide_layout_rels())
        pptx.writestr("ppt/notesMasters/notesMaster1.xml", notes_master_xml())
        pptx.writestr("ppt/notesMasters/_rels/notesMaster1.xml.rels", notes_master_rels())
        pptx.writestr("ppt/theme/theme1.xml", theme_xml())

        for idx, slide in enumerate(slides, start=1):
            if idx == 1:
                pptx.writestr(f"ppt/slides/slide{idx}.xml", cover_slide_xml())
                pptx.writestr(f"ppt/slides/_rels/slide{idx}.xml.rels", cover_slide_rels(idx))
            else:
                pptx.writestr(f"ppt/slides/slide{idx}.xml", slide_xml(idx, slide["title"]))
                pptx.writestr(f"ppt/slides/_rels/slide{idx}.xml.rels", slide_rels(idx))
            pptx.writestr(f"ppt/notesSlides/notesSlide{idx}.xml", notes_xml(slide))
            pptx.writestr(f"ppt/notesSlides/_rels/notesSlide{idx}.xml.rels", notes_rels(idx))
            if idx != 1:
                pptx.write(image_path(slide), f"ppt/media/{media_name(idx)}")


def main() -> None:
    slides = load_slides()
    write_pptx(slides)
    print(f"Created {OUT}")
    print(f"Slides: {len(slides)}")
    print(f"Slides with notes: {len(slides)}")


if __name__ == "__main__":
    main()
