export const styleGuide = {
  name: "dark-blueprint",
  referenceImage: "share/deck/refs/01-ref-blueprint.png",
  summary:
    "Dark navy blueprint grid, crisp cyan and electric-blue line work, precise rounded technical panels, small high-contrast labels, no decorative clutter.",
};

export const slides = [
  {
    n: 1,
    slug: "cover",
    title: "Build a Mini-GPT from scratch",
    type: "Cover",
    layout: "simple-title-cover",
    goal: "Open the talk with a simple title page and set the topic.",
    headline: "Build a Mini-GPT from scratch",
    subline: "Understand Transformer architecture and how it works.",
    bullets: [
      "Build a Mini-GPT from scratch",
      "Understand Transformer architecture and how it works",
      "Speaker: Molin",
      "Team: ECP CIS",
    ],
    visual:
      "A clean dark-blueprint cover with the title, subtitle, speaker, team, and a small Transformer flow diagram: tokens, a compact block stack, and next-token output.",
    labels: ["tokens", "Transformer block", "next token"],
    notes: [
      "Hello everyone. I am Molin from ECP CIS.",
      "Today we will talk about how to build a Mini-GPT from scratch.",
      "The goal is simple: use a small model to understand the Transformer architecture and how it works.",
      "Let's get started.",
    ],
    code: ["src/tokenizer.py", "src/model.py", "src/train.py"],
  },
  {
    n: 2,
    slug: "transformer-next-token",
    title: "Transformer Is the Foundation",
    type: "Context",
    layout: "source-rich-concept-flow",
    goal: "Set the technical context: Transformer is the main architecture behind many modern AI models, and GPT-style models predict the next token.",
    headline: "Transformer Is the Foundation",
    subline: "Attention Is All You Need introduced the architecture behind GPT-style models.",
    bullets: [
      "Modern AI models share this architecture",
      "Attention Is All You Need, 2017",
      "GPT reads context and predicts the next token",
    ],
    sources: [
      {
        label: "Paper",
        url: "https://arxiv.org/abs/1706.03762",
        display: "arxiv.org/abs/1706.03762",
      },
    ],
    visual:
      "Dark-blueprint slide with one clear information panel and one visual flow. Show Attention Is All You Need as a paper card, connect it to a compact Transformer block, feed context token boxes into the block, and show one highlighted next-token output. Include a small source chip for the paper URL.",
    labels: ["paper", "Transformer", "context tokens", "next token"],
    notes: [
      "Before we build anything, let us set the map.",
      "Many modern AI models are based on the Transformer architecture. The Transformer was introduced in the paper Attention Is All You Need in 2017.",
      "For a GPT-style model, the main job is simple to say: read the tokens so far, and predict the next token.",
      "The paper link is on the slide, so you can find the original source after the talk.",
      "In this talk, we will see the pieces that make this possible.",
    ],
    code: ["src/model.py", "src/train.py"],
  },
  {
    n: 3,
    slug: "why-build-microgpt",
    title: "Why MicroGPT",
    type: "Project Setup",
    layout: "source-rich-project-pipeline",
    goal: "Introduce the learning project: use a tiny MicroGPT-style name generator so the Transformer ideas become concrete.",
    headline: "Why MicroGPT",
    subline: "A tiny, inspectable GPT makes the ideas concrete.",
    bullets: [
      "Tiny, inspectable GPT-style project",
      "Inspired by Andrej Karpathy and trained on names",
      "Full path: tokens -> blocks -> logits -> sampling",
    ],
    sources: [
      {
        label: "MicroGPT code",
        url: "https://karpathy.ai/microgpt.html",
        display: "karpathy.ai/microgpt.html",
      },
      {
        label: "makemore",
        url: "https://github.com/karpathy/makemore",
        display: "github.com/karpathy/makemore",
      },
    ],
    visual:
      "Dark-blueprint slide with one clear information panel and one project pipeline. Show a 32K names dataset flowing into a small MicroGPT training loop, then output generated name samples. Include compact source chips for MicroGPT code and makemore.",
    labels: ["32K names", "MicroGPT", "train", "new names"],
    notes: [
      "If we only talk about concepts, Transformer can feel too abstract.",
      "So we will use a small project and build it step by step. The project is inspired by Andrej Karpathy's MicroGPT code and makemore style.",
      "The model trains on about 32K names. After training, it can generate new name-like strings.",
      "The source links are on the slide, so you can explore the original code and dataset later.",
      "The task is small, but it contains the same path: tokens, Transformer blocks, logits, loss, and sampling.",
    ],
    code: ["src/tokenizer.py", "src/model.py", "src/train.py"],
  },
  {
    n: 4,
    slug: "function-view",
    title: "A Neural Network Is a Function",
    type: "Neural Network Basics",
    layout: "linear-progression",
    goal: "Start from the simplest mental model of a neural network.",
    headline: "Numbers go in, scores come out",
    subline: "A neural network is a function with parameters.",
    bullets: ["Input numbers", "Parameter weights", "Output scores"],
    visual:
      "Clean function box diagram: input vector x enters f(x; theta), output scores leave the box, with theta shown as adjustable knobs.",
    labels: ["x", "parameters", "scores"],
    notes: [
      "Before we say Transformer, let us start with a simple idea. A neural network is a function.",
      "The input is a group of numbers. The function has parameters, also called weights. The output is another group of numbers.",
      "For our Mini-GPT, the output numbers are scores for possible next characters. At first these scores are bad. Training changes the parameters so the scores become more useful.",
    ],
    code: ["src/model.py: Linear"],
  },
  {
    n: 5,
    slug: "single-neuron",
    title: "One Neuron",
    type: "Neural Network Basics",
    layout: "hub-spoke",
    goal: "Explain weighted sum and activation with a small example.",
    headline: "A neuron mixes inputs",
    subline: "weighted sum -> nonlinearity -> one new number",
    bullets: ["Multiply each input by a weight", "Add them together", "Pass through ReLU"],
    visual:
      "A precise neuron diagram with three input lines, weights on each line, a sum node, and a ReLU gate producing one output.",
    labels: ["inputs", "weights", "sum", "ReLU", "output"],
    notes: [
      "A single neuron is a very small computation. It takes several input numbers, multiplies them by weights, and adds the results.",
      "Then it usually applies a nonlinearity. In this project, the MLP uses ReLU. ReLU is simple: negative values become zero, positive values stay positive.",
      "One neuron is not enough for GPT, but it gives us the basic building block: weighted information plus a simple nonlinear step.",
    ],
    code: ["src/model.py: relu"],
  },
  {
    n: 6,
    slug: "mlp-stack",
    title: "From Neuron to MLP",
    type: "Neural Network Basics",
    layout: "hierarchical-layers",
    goal: "Show how many neurons become a small network.",
    headline: "An MLP is layers of neurons",
    subline: "Linear -> ReLU -> Linear computes new features.",
    bullets: ["Layer 1 creates hidden features", "ReLU keeps useful positive signals", "Layer 2 maps back to model size"],
    visual:
      "Layered MLP blueprint: input vector, first linear layer, ReLU row, second linear layer, output vector.",
    labels: ["input", "Linear", "ReLU", "Linear", "output"],
    notes: [
      "When we place many neurons side by side, we get a layer. When we stack layers, we get a small neural network called an MLP.",
      "In our Mini-GPT block, the MLP is Linear, then ReLU, then Linear. It does not talk across time. It works inside each token position.",
      "This is important. Attention is the part that reads other positions. The MLP is the part that computes new features at the current position.",
    ],
    code: ["src/model.py: FeedForward"],
  },
  {
    n: 7,
    slug: "prediction-loss",
    title: "Prediction and Loss",
    type: "Training Basics",
    layout: "dashboard",
    goal: "Connect scores to probability and loss.",
    headline: "Loss measures surprise",
    subline: "If the target is n, we want high probability on n.",
    bullets: ["Logits are raw scores", "Softmax gives probabilities", "Cross-entropy rewards the target"],
    visual:
      "Probability bar chart for next characters after den, with n highlighted and a loss gauge beside it.",
    labels: ["logits", "softmax", "target n", "loss"],
    notes: [
      "The model outputs logits. Logits are raw scores. They are not probabilities yet.",
      "Softmax turns these scores into probabilities. If the true next character is n, then a good model gives high probability to n.",
      "Cross-entropy loss is high when the correct character has low probability. It is low when the correct character has high probability. So loss gives us one number to improve.",
    ],
    code: ["src/model.py: softmax_cross_entropy"],
  },
  {
    n: 8,
    slug: "backprop-update",
    title: "Backprop and Update",
    type: "Training Basics",
    layout: "circular-flow",
    goal: "Explain how training changes parameters.",
    headline: "Training is a loop",
    subline: "predict -> loss -> gradients -> update",
    bullets: ["Backprop computes gradients", "AdamW changes weights", "Repeat many times"],
    visual:
      "Circular training loop diagram with four nodes and small arrows flowing around the circle.",
    labels: ["predict", "loss", "gradients", "AdamW"],
    notes: [
      "Training is not mysterious. We run the model, compute loss, compute gradients, and update the parameters.",
      "Backpropagation tells each parameter how it affected the loss. AdamW uses those gradients to move the parameter a small amount.",
      "After many updates, the model becomes less surprised by real training examples. In our case, it becomes better at predicting the next character in a name.",
    ],
    code: ["src/model.py: Tensor.backward", "src/train.py: AdamW"],
  },
  {
    n: 9,
    slug: "name-data",
    title: "Names as Tiny Documents",
    type: "Data",
    layout: "two-columns",
    goal: "Show the MicroGPT name-data framing.",
    headline: "Each name is a tiny document",
    subline: "BOS dennis BOS teaches start and stop.",
    bullets: ["Use short names", "Wrap with BOS", "Train every next-character step"],
    visual:
      "Two-column blueprint: raw name list on the left and wrapped token sequence boxes on the right.",
    labels: ["dennis", "cis", "molin", "BOS"],
    notes: [
      "Now we connect the neural network to the data. In a MicroGPT-style name model, each name is a tiny document.",
      "We add a special token called BOS. It can mean beginning of sequence, and in this small project it also marks the end.",
      "So the name dennis becomes BOS, d, e, n, n, i, s, BOS. This one sequence creates many next-character training examples.",
    ],
    code: ["src.train.build_name_token_stream"],
  },
  {
    n: 10,
    slug: "next-token-task",
    title: "The Next-Token Task",
    type: "Core Idea",
    layout: "linear-progression",
    goal: "Show shifted input and target windows.",
    headline: "Input is shifted against target",
    subline: "BOS d e n predicts d e n n.",
    bullets: ["Same sequence", "Shift by one step", "Many targets from one name"],
    visual:
      "Aligned two-row sequence diagram: input row BOS d e n, target row d e n n, with vertical arrows between positions.",
    labels: ["input", "target", "shift"],
    notes: [
      "The next-token task is made by shifting the sequence by one step.",
      "The input row might be BOS, d, e, n. The target row is d, e, n, n. At each position, the model predicts the next character.",
      "This is very efficient for learning. One short name gives many small prediction tasks. The Transformer learns from all positions at the same time.",
    ],
    code: ["src.train.get_batch"],
  },
  {
    n: 11,
    slug: "tokenizer-idea",
    title: "What a Tokenizer Does",
    type: "Tokenizer",
    layout: "linear-progression",
    goal: "Define tokenizer as the boundary from text to ids.",
    headline: "Text must become token ids",
    subline: "The model reads numbers, not letters on a screen.",
    bullets: ["Split text into tokens", "Map tokens to ids", "Decode ids back to text"],
    visual:
      "Three-stage tokenizer pipeline: text string, token boxes, integer id boxes, then reverse decode arrow.",
    labels: ["text", "tokens", "ids", "decode"],
    notes: [
      "A tokenizer is the boundary between human text and model input.",
      "The model cannot read the string directly. The tokenizer splits the text into tokens, maps each token to an integer id, and can later decode ids back into text.",
      "For our small model, tokens are characters. For large GPT systems, tokens are often pieces of words. The idea is the same: text becomes ids.",
    ],
    code: ["src/tokenizer.py: CharTokenizer"],
  },
  {
    n: 12,
    slug: "tiktoken-example",
    title: "Tokenizer Example: I love CIS",
    type: "Tokenizer",
    layout: "binary-comparison",
    goal: "Compare subword tokenization to character tokenization.",
    headline: "Real GPTs often use subword tokens",
    subline: "I love CIS may become a few word pieces, not characters.",
    bullets: ["tiktoken style: word pieces", "Mini-GPT style: characters", "Both output integer ids"],
    visual:
      "Side-by-side tokenizer comparison for the phrase I love CIS: subword chunks on one side, character chunks on the other.",
    labels: ["I", " love", " CIS", "I", "l", "o", "v", "e", "CIS"],
    notes: [
      "Let us use the text I love CIS. A production GPT tokenizer, such as tiktoken, may split this into word pieces. For example, I, space-love, and space-CIS may be separate tokens depending on the vocabulary.",
      "Our Mini-GPT tokenizer is simpler. It splits the same text into characters.",
      "The split is different, but the final interface is the same. The model receives integer ids. It does not receive the original text string.",
    ],
    code: ["src/tokenizer.py"],
  },
  {
    n: 13,
    slug: "char-tokenizer-dennis",
    title: "Character Tokenizer: Dennis",
    type: "Tokenizer",
    layout: "dashboard",
    goal: "Make the project tokenizer fully concrete.",
    headline: "Dennis becomes character ids",
    subline: "BOS d e n n i s BOS",
    bullets: ["Small vocabulary", "Visible mapping", "Easy round-trip test"],
    visual:
      "Tokenizer table showing BOS, d, e, n, i, s mapped to integer ids, plus a Dennis token sequence below.",
    labels: ["BOS", "d", "e", "n", "i", "s", "ids"],
    notes: [
      "For the name Dennis, we lowercase it for the tiny model and treat each character as a token.",
      "The wrapped sequence is BOS, d, e, n, n, i, s, BOS. Each symbol has an id from the tokenizer vocabulary.",
      "This is simple enough to test directly. If we encode and then decode a name, we should get the same name back, except for the special tokens we choose to add or remove.",
    ],
    code: ["tests/test_core.py: tokenizer round trip"],
  },
  {
    n: 14,
    slug: "ids-are-not-meaning",
    title: "Token IDs Are Not Meaning",
    type: "Embedding",
    layout: "quote-callout",
    goal: "Prevent the common misunderstanding that ids contain meaning.",
    headline: "An id is only a label",
    subline: "Token 14 is not more meaningful than token 4.",
    bullets: ["Ids choose rows", "Distances between ids do not matter", "Learning starts in embeddings"],
    visual:
      "Blueprint warning-style diagram: integer id boxes point to table rows, with a crossed-out ruler between id numbers.",
    labels: ["id", "row lookup", "not distance"],
    notes: [
      "A very common mistake is to think token ids have meaning by themselves.",
      "They do not. If d has id 4 and n has id 14, that does not mean n is ten units away from d in a useful language space.",
      "The id is just an address. It chooses a row in an embedding table. The vector in that row is what the model will learn and use.",
    ],
    code: ["src/model.py: Embedding"],
  },
  {
    n: 15,
    slug: "token-embedding",
    title: "Token Embedding",
    type: "Embedding",
    layout: "comparison-matrix",
    goal: "Show embedding lookup as table selection.",
    headline: "Embedding is a learned table",
    subline: "id -> vector",
    bullets: ["One row per token", "Vector size is model dimension", "Rows change during training"],
    visual:
      "Embedding matrix diagram: token ids on the left select colored vector rows in a table.",
    labels: ["id 4", "E[4]", "D dims"],
    notes: [
      "The token embedding table has one row for each token in the vocabulary.",
      "When the model sees token id 4, it selects row 4 from the table. That row is a vector. The vector length is the model dimension.",
      "At the start, these vectors are random. During training, the vectors move so useful character patterns become easier for the Transformer to compute.",
    ],
    code: ["src/model.py: Embedding.forward"],
  },
  {
    n: 16,
    slug: "position-embedding",
    title: "Position Embedding",
    type: "Embedding",
    layout: "linear-progression",
    goal: "Explain why order must be added.",
    headline: "Position tells the model where a token is",
    subline: "The two n tokens in denn share a token id, but not a position.",
    bullets: ["Same token can appear twice", "Position vector is different", "Token + position becomes hidden state"],
    visual:
      "Two rows showing token vectors and position vectors added together for d e n n, with the two n tokens highlighted differently.",
    labels: ["token", "position", "add", "hidden"],
    notes: [
      "A token embedding tells the model what symbol it is. But the model also needs to know where the symbol is.",
      "In the prefix denn, the two n characters have the same token id. Without position information, they would start with the same vector.",
      "So Mini-GPT adds a position embedding. Token vector plus position vector becomes the first hidden state for each position.",
    ],
    code: ["src/model.py: MiniGPT.forward"],
  },
  {
    n: 17,
    slug: "hidden-stream",
    title: "The Hidden Stream",
    type: "Embedding",
    layout: "linear-progression",
    goal: "Introduce the vector stream that moves through the model.",
    headline: "Each position carries a vector",
    subline: "The Transformer edits these vectors layer by layer.",
    bullets: ["Shape: B, T, D", "One vector per token position", "Blocks update the stream"],
    visual:
      "Tensor stream diagram: a row of token positions, each with a vertical vector bar, flowing into Transformer blocks.",
    labels: ["B", "T", "D", "hidden stream"],
    notes: [
      "After token and position embeddings are added, the model has a hidden stream.",
      "The shape is B, T, D. B is batch size. T is the number of positions. D is the vector size.",
      "Each position has its own vector. The Transformer block will update these vectors. Attention lets positions share information. The MLP computes new features inside each position.",
    ],
    code: ["src/model.py: MiniGPT.forward"],
  },
  {
    n: 18,
    slug: "decoder-only-map",
    title: "MicroGPT Decoder-Only Map",
    type: "Transformer",
    layout: "hierarchical-layers",
    goal: "Show the full MicroGPT path.",
    headline: "Mini-GPT is decoder-only",
    subline: "ids -> embeddings -> blocks -> logits -> next token",
    bullets: ["No encoder", "Causal self-attention", "One linear head"],
    visual:
      "Full dark blueprint architecture similar to the reference image: token ids, embeddings, repeated blocks, norm, linear head, logits.",
    labels: ["Token IDs", "Embedding", "Transformer Block", "Logits", "Next Token"],
    notes: [
      "Now we can look at the full MicroGPT-style architecture.",
      "It is decoder-only. That means there is no separate encoder. The model reads the previous tokens and predicts the next token.",
      "The path is simple to say: token ids become embeddings, embeddings pass through repeated Transformer blocks, a final norm prepares the vectors, and a linear head produces logits for the next token.",
    ],
    code: ["src/model.py: MiniGPT"],
  },
  {
    n: 19,
    slug: "block-map",
    title: "Inside One Transformer Block",
    type: "Transformer",
    layout: "hierarchical-layers",
    goal: "Show the two main jobs inside a block.",
    headline: "A block reads, then computes",
    subline: "attention communicates; MLP computes",
    bullets: ["RMSNorm before each sublayer", "Residual adds keep the stream", "Attention + MLP repeat"],
    visual:
      "Zoom-in blueprint of one Transformer block with RMSNorm, Attention, residual add, RMSNorm, MLP, residual add.",
    labels: ["RMSNorm", "Attention", "Add", "MLP"],
    notes: [
      "A Transformer block has two main jobs.",
      "First, attention lets one position read information from earlier positions. Second, the MLP computes new features inside each position.",
      "RMSNorm helps keep vector scale stable. Residual connections add the new information back to the old stream. This makes the model easier to train and easier to think about.",
    ],
    code: ["src/model.py: TransformerBlock"],
  },
  {
    n: 20,
    slug: "attention-intuition",
    title: "Attention Intuition",
    type: "Attention",
    layout: "hub-spoke",
    goal: "Explain attention before formulas.",
    headline: "Attention is content lookup",
    subline: "The current position asks: what earlier information matters?",
    bullets: ["Look only left", "Score visible positions", "Mix useful values"],
    visual:
      "Hub-spoke diagram where the final n in denn sends lookup rays to BOS, d, e, and the previous n.",
    labels: ["current n", "visible context", "lookup"],
    notes: [
      "Attention is easier to understand as content lookup.",
      "Imagine the final n in the prefix denn. To predict the next character, it may need to read earlier context. It can look left at d, e, and the previous n.",
      "Attention gives the model a learned way to score those visible positions and mix their information into the current vector.",
    ],
    code: ["src/model.py: CausalSelfAttention"],
  },
  {
    n: 21,
    slug: "qkv-roles",
    title: "Q, K, V Roles",
    type: "Attention",
    layout: "three-columns",
    goal: "Explain query, key, and value with simple words.",
    headline: "Q asks, K matches, V carries",
    subline: "Three learned projections make lookup possible.",
    bullets: ["Query: what do I need?", "Key: what do I contain?", "Value: what should I send?"],
    visual:
      "Three-column blueprint diagram for Query, Key, Value, with arrows from the same hidden vector into Wq, Wk, Wv.",
    labels: ["Q", "K", "V", "Wq", "Wk", "Wv"],
    notes: [
      "For each position, the model makes three vectors: query, key, and value.",
      "The query is like a question from the current position: what information do I need? The key is like a description of each visible position: what do I contain?",
      "The value is the information that will be sent if that position is useful. Q and K decide the attention weights. V is what gets mixed.",
    ],
    code: ["src/model.py: CausalSelfAttention.forward"],
  },
  {
    n: 22,
    slug: "attention-scores",
    title: "Attention Scores",
    type: "Attention",
    layout: "dashboard",
    goal: "Show dot product, mask, and softmax as a sequence.",
    headline: "Scores become weights",
    subline: "Q dot K, apply mask, softmax.",
    bullets: ["Dot product measures match", "Mask removes future", "Softmax normalizes weights"],
    visual:
      "Attention score matrix for BOS d e n n, with the final row highlighted and future cells blocked.",
    labels: ["QK^T", "mask", "softmax", "weights"],
    notes: [
      "The attention score is usually made with a dot product between query and key.",
      "If the query and key match well, the score is high. If they do not match, the score is low.",
      "Then the causal mask blocks future positions. Finally, softmax turns the visible scores into weights. Those weights decide how much value information will be mixed into the current position.",
    ],
    code: ["src/model.py: causal_mask"],
  },
  {
    n: 23,
    slug: "qkv-animation-plan",
    title: "QKV Animation Plan",
    type: "Attention",
    layout: "winding-roadmap",
    goal: "Describe the animation/video sequence requested for QKV.",
    headline: "Animate QKV in four beats",
    subline: "project -> compare -> mask -> mix",
    bullets: ["1. Hidden vectors split into Q K V", "2. Current Q compares with visible K", "3. Mask hides the future", "4. Weights mix V"],
    visual:
      "Storyboard strip with four blueprint frames showing the QKV attention process over the tokens d e n n.",
    labels: ["project", "compare", "mask", "mix"],
    notes: [
      "This slide is a clear plan for the QKV animation.",
      "First, each hidden vector is projected into Q, K, and V. Second, the current query compares with the keys from visible positions. Third, the mask removes future positions. Fourth, the final weights mix the value vectors.",
      "Even if we show it as an animation, the idea is still simple: ask, match, block the future, and mix useful information.",
    ],
    code: ["src/model.py: CausalSelfAttention"],
  },
  {
    n: 24,
    slug: "causal-mask",
    title: "Causal Mask",
    type: "Attention",
    layout: "comparison-matrix",
    goal: "Explain why GPT cannot look right during training.",
    headline: "The model must not cheat",
    subline: "Position t can only read positions <= t.",
    bullets: ["Training sees full sequences", "Mask hides future tokens", "Generation stays left-to-right"],
    visual:
      "Lower-triangular causal mask matrix for tokens BOS d e n n, with allowed cells glowing cyan and blocked cells dark.",
    labels: ["allowed", "blocked", "future"],
    notes: [
      "During training, we give the model a whole window of tokens. Without a mask, a position could look at the answer on its right.",
      "That would be cheating. GPT must learn to predict from the past, because during generation the future does not exist yet.",
      "The causal mask solves this. Each position can read itself and earlier positions, but it cannot read later positions.",
    ],
    code: ["src/model.py: causal_mask"],
  },
  {
    n: 25,
    slug: "multi-head",
    title: "Multi-Head Attention",
    type: "Attention",
    layout: "three-columns",
    goal: "Explain why multiple heads are useful.",
    headline: "Several heads read in several ways",
    subline: "One head may track spelling, another may track endings.",
    bullets: ["Split channels", "Run attention in parallel", "Merge heads back"],
    visual:
      "Three parallel attention head lanes over the same Dennis token sequence, each with a different highlighted relation.",
    labels: ["head 1", "head 2", "head 3", "merge"],
    notes: [
      "Multi-head attention means the model runs several attention operations in parallel.",
      "Each head gets part of the vector channels. One head might learn local spelling rhythm. Another might learn likely endings. Another might notice repeated letters like n n.",
      "After the heads read context in different ways, their outputs are merged back into one vector stream.",
    ],
    code: ["src/model.py: _split_heads", "src/model.py: _merge_heads"],
  },
  {
    n: 26,
    slug: "rmsnorm-residual",
    title: "RMSNorm and Residuals",
    type: "Transformer",
    layout: "linear-progression",
    goal: "Explain stability pieces in simple terms.",
    headline: "Keep the stream stable",
    subline: "Normalize, compute, add back.",
    bullets: ["RMSNorm controls scale", "Residual adds keep old information", "Training becomes smoother"],
    visual:
      "Blueprint pipe diagram: hidden stream goes through RMSNorm, sublayer, plus sign, and returns to the main stream.",
    labels: ["RMSNorm", "sublayer", "add"],
    notes: [
      "RMSNorm and residual connections are not the flashiest parts, but they matter.",
      "RMSNorm keeps vector scale under control before attention or the MLP. The residual connection adds the new result back to the old stream.",
      "This means each block can make an edit instead of replacing everything. That makes deep stacks easier to train.",
    ],
    code: ["src/model.py: RMSNorm"],
  },
  {
    n: 27,
    slug: "mlp-in-block",
    title: "The MLP Inside the Block",
    type: "Transformer",
    layout: "hierarchical-layers",
    goal: "Connect the early MLP explanation to the Transformer block.",
    headline: "The MLP computes at each position",
    subline: "Attention shares information; MLP transforms it.",
    bullets: ["Same MLP idea as before", "Applied to every token position", "Uses Linear -> ReLU -> Linear"],
    visual:
      "Zoomed block diagram showing one token vector entering a small MLP stack, while other positions run the same MLP independently.",
    labels: ["Linear", "ReLU", "Linear", "per position"],
    notes: [
      "Now the earlier MLP idea comes back.",
      "Inside each Transformer block, after attention has shared information, the MLP computes new features at each position. It uses Linear, ReLU, and Linear.",
      "The same MLP weights are applied to every position. So attention is communication across positions, while the MLP is computation inside each position.",
    ],
    code: ["src/model.py: FeedForward"],
  },
  {
    n: 28,
    slug: "linear-head",
    title: "Linear Head to Logits",
    type: "Output",
    layout: "dashboard",
    goal: "Show how hidden vectors become next-token scores.",
    headline: "The final vector becomes vocabulary scores",
    subline: "D-dimensional hidden state -> V logits.",
    bullets: ["Use the last position for generation", "One score per token id", "Softmax turns scores into probabilities"],
    visual:
      "Final hidden vector entering a linear head, expanding into a vertical list of vocabulary logits for next characters.",
    labels: ["hidden D", "linear head", "logits V"],
    notes: [
      "After the Transformer blocks, the model still has one vector for each position.",
      "A final linear head maps each vector from model dimension D to vocabulary size V. That gives one logit score for each possible next token.",
      "During generation, we usually read the logits at the final position. Those logits tell us what the model thinks the next token could be.",
    ],
    code: ["src/model.py: MiniGPT.forward"],
  },
  {
    n: 29,
    slug: "training-loop-code",
    title: "Training Loop in Code",
    type: "Implementation",
    layout: "split-screen",
    goal: "Connect the theory to the training function.",
    headline: "The code is the loop",
    subline: "batch, forward, loss, backward, update",
    bullets: ["Get a batch", "Run forward pass", "Backprop and step AdamW"],
    visual:
      "Split-screen blueprint with compact pseudocode on the left and a training loop diagram on the right.",
    labels: ["get_batch", "forward", "loss", "step"],
    notes: [
      "Now the code should look familiar.",
      "The training loop gets a batch of token ids and targets. It runs the model forward. It computes the loss. Then it clears old gradients, runs backward, and calls the optimizer step.",
      "This is the same loop we saw near the beginning. The only difference is that now the function is a Transformer instead of a simple MLP.",
    ],
    code: ["src/train.py: train"],
  },
  {
    n: 30,
    slug: "sampling-loop",
    title: "Sampling Loop",
    type: "Implementation",
    layout: "linear-progression",
    goal: "Explain generation as repeated forward passes.",
    headline: "Generation reuses the same model",
    subline: "crop context -> logits -> sample -> append",
    bullets: ["Start from BOS or a prompt", "Read final-position logits", "Sample one token and repeat"],
    visual:
      "Generation loop diagram with token context growing one box at a time from d e n to dennis.",
    labels: ["context", "logits", "sample", "append"],
    notes: [
      "Generation is not a new model. It reuses the same forward pass.",
      "We start from BOS or from a prompt like den. We crop the context if it is longer than block size. We run the model and read the logits at the last position.",
      "Then we sample one token, append it, and repeat. When the model samples BOS again, we stop and decode the name.",
    ],
    code: ["src/train.py: generate", "src/train.py: generate_name"],
  },
  {
    n: 31,
    slug: "what-to-inspect",
    title: "What to Inspect",
    type: "Engineering",
    layout: "dashboard",
    goal: "Give the audience practical checkpoints.",
    headline: "Make the invisible visible",
    subline: "Tiny models are useful because we can inspect them.",
    bullets: ["Tokenizer round trips", "Tensor shapes", "Attention mask", "Loss and samples"],
    visual:
      "Testing dashboard with four panels: tokenizer, shapes, attention mask, generated samples.",
    labels: ["tests", "shapes", "mask", "samples"],
    notes: [
      "The best part of a tiny implementation is visibility.",
      "We can test that the tokenizer round-trips text correctly. We can print shapes like B, T, and D. We can inspect the causal mask. We can watch loss go down and samples become more name-like.",
      "This habit is useful even when working with larger systems. Always connect the concept to something you can check.",
    ],
    code: ["tests/test_core.py"],
  },
  {
    n: 32,
    slug: "recap",
    title: "Recap",
    type: "Closing",
    layout: "linear-progression",
    goal: "Close with the full connected path.",
    headline: "One path from text to generated names",
    subline: "text -> ids -> vectors -> attention -> logits -> sample",
    bullets: ["Neural networks are trainable functions", "Tokenizer and embeddings create model input", "Transformer blocks improve next-token predictions"],
    visual:
      "Full end-to-end blueprint ribbon from raw names to generated name samples, with major stages marked.",
    labels: ["text", "ids", "vectors", "attention", "logits", "sample"],
    notes: [
      "Let us recap the whole path.",
      "A neural network is a trainable function. Our tokenizer turns text into ids. Embeddings turn ids and positions into vectors. Transformer blocks update those vectors. Attention lets positions read earlier context. The linear head produces logits, and sampling turns logits into new characters.",
      "That is the core idea of GPT, shown in a tiny model we can inspect.",
    ],
    code: ["src/tokenizer.py", "src/model.py", "src/train.py"],
  },
];
